site_name: plantiSMASH Documentation
nav:
    - Home: index.md
    - Using plantiSMASH:
        - Introduction: intro.md
        - Submitting jobs on the webserver: website_submission.md
        - Results page: understanding_output/overview.md
        - plantiSMASH database: understanding_output/database.md
    - Generic modules:
        - BGC detection: modules/clusterrules.md
        - ClusterBLAST: modules/clusterblast.md
        - KnownClusterBLAST: modules/knownclusterblast.md
        - Coexpress: modules/coexpress.md
        - Subgroup Finder: modules/subgroup.md
        - TFBS Finder: modules/tfbs.md
    - Specific modules: 
        - Cyclopeptide Finder: modules/cyclopeptides.md
    - Local Installation:
        - Installation: install.md
        - Starting command line runs: command_line.md
    - Change Log:
        - Overview: changelog/index.md
        - Version 2.0: changelog/2.0.md
        - Version 1.0: changelog/1.0.md
    - FAQ: faq.md
    - Glossary: glossary.md
    - About: about.md
theme:
    name: readthedocs
    custom_dir: custom_theme
markdown_extensions:
    - footnotes
    - toc:
        permalink: "#"
    - pymdownx.details # Enables collapsible sections
    - pymdownx.superfences # Ensures proper code block rendering
plugins:
  - search
  - git-revision-date
extra_css: 
  - css/extra.css 
extra: 
extra:
  extra:
  copyright: >
    © 2025 <a href="https://github.com/elenadelpup" target="_blank">Elena Del Pup</a> et al. 
    under the <a href="https://opensource.org/licenses/MIT" target="_blank">MIT License</a>
    |
    <a href="https://github.com/plantismash/plantismash" target="_blank" style="text-decoration:none;">
      <img src="https://cdn.jsdelivr.net/npm/simple-icons@v5/icons/github.svg"
           alt="GitHub"
           style="height:1em;vertical-align:middle;margin-right:4px;">
      <strong>plantiSMASH</strong> GitHub
    </a>
    under the 
    <a href="https://github.com/plantismash/plantismash/blob/master/LICENSE.txt" target="_blank">GNU AGPL v3.0 License</a>
    |
    <a href="https://github.com/plantismash/documentation/issues" target="_blank" style="text-decoration:none;">
      <img src="https://cdn.jsdelivr.net/npm/simple-icons@v5/icons/github.svg"
           alt="GitHub Issues"
           style="height:1em;vertical-align:middle;margin-right:4px;">
      <strong>Feedback or issues?</strong>
    </a>