site_name: PlantiSMASH Documentation
nav:
    - Home: index.md
    - Using PlantiSMASH:
        - Introduction: intro.md
        - Submitting jobs on the webserver: website_submission.md
        - Results page: understanding_output/overview.md
        - Region concept: understanding_output/regions.md
    - Module-specific information:
        - BGC detection: modules/clusterrules.md
        - TFBS Finder: modules/tfbs.md
    - Local Installation:
        - Installation: install.md
        - Starting command line runs: command_line.md
    - Change Log:
        - Version 2.0: changelog/2.0.md
        - Version 1.0: changelog/1.0.md
    - FAQ: faq.md
    - Glossary: glossary.md
    - About: about.md
theme:
    name: readthedocs
    custom_dir: custom_theme
markdown_extensions:
    - footnotes
    - toc:
        permalink: "#"
    - pymdownx.details # Enables collapsible sections
    - pymdownx.superfences # Ensures proper code block rendering
plugins:
  - search
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
extra_css: 
  - css/extra.css 
extra: 
    copyright: '© 2025 <a href="https://github.com/elenadelpup" target="_blank">Elena Del Pup</a>'

