name: publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      run: /usr/bin/git clone https://github.com/${GITHUB_REPOSITORY}.git ${GITHUB_WORKSPACE}
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build the docs
      run: |
        mkdocs build
    - name: Deploy the docs
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        eval $(ssh-agent)
        echo "exec cat" > ap-cat.sh
        chmod a+x ap-cat.sh
        export DISPLAY=1
        echo "${{secrets.SSH_PASSPHRASE}}" | SSH_ASKPASS=./ap-cat.sh ssh-add ~/.ssh/id_ed25519
        rm ap-cat.sh
        rsync --delete -rlpcP -e ssh site/ deploys@front01.secondarymetabolites.org:/var/www/as-docs/
